{
    'name': 'Funeral Assurance System',
    'version': '1.0',
    'category': 'Sales/Funeral',
    'summary': 'Manage Funeral Assurance static data, agents, and policies.',
    'description': 'A comprehensive system to manage funeral assurance business including agents, products, targets, commissions, etc.',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron_jobs.xml',
        'reports/payment_receipt.xml',
        'reports/policy_schedule.xml',
        'reports/sum_assured_claim.xml',
        'reports/funeral_services_claim.xml',
        'reports/proposal_form.xml',
        'views/dashboard_view.xml',
        'views/funeral_menus.xml',
        'views/proposal_view.xml',
        'views/policy_view.xml',
        'views/payment_view.xml',
        'views/claim_view.xml',
        'views/commission_view.xml',
        'views/city_view.xml',
        'views/agent_view.xml',
        'views/vehicle_view.xml',
        'views/tombstone_view.xml',
        'views/commissioner_view.xml',
        'views/static_data_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
