from . import city
from . import agent
from . import static_data
from . import product
from . import admin_policy
from . import target
from . import dashboard
from . import proposal
from . import policy
from . import payment
from . import claim
from . import commission
from . import vehicle
from . import tombstone
from . import commissioner
from . import stock
from . import res_config_settings
from . import report_wizard